# https://github.com/facebook/docusaurus/issues/10645 seems unsolvable
# without upstream change, do not let it block the upgrade
nodeLinker: node-modules

# debug is for https://github.com/esxjs/esx/issues/18
# rest are for https://github.com/facebook/docusaurus/issues/10645
packageExtensions:
  '@docusaurus/theme-common@*':
    dependencies:
      '@docusaurus/plugin-content-docs': '*'
  '@docusaurus/theme-mermaid@*':
    dependencies:
      langium: '*'
    peerDependencies:
      '@docusaurus/theme-common': '*'
  debug@*:
    dependencies:
      supports-color: '*'
  langium@*:
    dependencies:
      '@chevrotain/regexp-to-ast': '*'
      vscode-jsonrpc: '*'
      vscode-languageserver-types: '*'
